FROM php:8.2-fpm-alpine3.16

WORKDIR /app

RUN apk add \
	composer \
	npm \
	libpq-dev

RUN apk add \
	php-tokenizer \
	php-xml \
	php-pdo \
	php-pdo_pgsql \
	php-dom \
	php-xmlwriter \
	php-curl \
	php-openssl \
	php-mbstring \
	php-gd \
	php-fileinfo
	
# PHP Postgres PDO

RUN docker-php-ext-install pdo_pgsql

COPY . /app
COPY entrypoint.sh /

# RUN 

CMD ["sh", "/entrypoint.sh"]